spring.application.name=Loan-API


# ===============================
# SERVER CONFIG
# ===============================
server.port = 122
# ===============================
# DATASOURCE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/loandb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# LOGGING (Optional but useful)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.loandemo.Loan.API=DEBUG
logging.file.name=logs/loan-api.log
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

# ===============================
# SESSION MANAGEMENT (Custom)
# ===============================
app.session.expiry-minutes=30
app.session.cleanup-cron=0 */5 * * * *


#================================
# EMAIL CONFIG
#================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL
spring.mail.password=mocw qwet wfsd u232
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay Test Credentials
razorpay.key.id=rzp_test_e3r4t5t
razorpay.key.secret=sderftgyh67845

# Optional - Currency
razorpay.currency=INR

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
